site: AL
read_csv_opts:
    - header: 0
      parse_dates: ["TIMESTAMP"]
      index_col: "TIMESTAMP"
      na_values: ["-99999", "99999", "-9999", "9999", "-6999", "-7777", "NA", "NAN"]
    - header: 1
      skiprows: [2, 3]
      parse_dates: ["TIMESTAMP"]
      index_col: "TIMESTAMP"
      na_values: ["-99999", "99999", "-9999", "9999", "-6999", "-7777", "NA", "NAN"]
    - header: 0
      na_values: ["-99999", "99999", "-9999", "9999", "-6999", "-7777", "NA", "NAN"]
      parse_dates: null
      index_col: null
conversions:
    2020-01-01 00:00:00:
      TA_Avg:
        scalar: 1
        offset: 0
        lower: -10
        upper: 50
      RH_Avg:
        scalar: 1
        lower: 1
        upper: 100
      PA:
        scalar: 1
        lower: 85
        upper: 105
      PAR_1_Avg:
        scalar: 151.74506828528072
        offset: 0
        lower: -5
        upper: 3000
      PAR_2_Avg:
        scalar: 150.60240963855424
        offset: 0
        lower: -5
        upper: 3000
      SW_IN_Avg:
        scalar: 75.35795026375283
        offset: 0
        lower: -150
        upper: 1500
      SW_OUT_Avg:
        scalar: 94.33962264150944
        offset: 0
        lower: -150
        upper: 3000
      LW_IN_Avg:
        scalar: 105.70824524312896
        offset: 5.67 * 10**-8 * (CNR4TC_Avg + 273.15) ** 4
        lower: -150
        upper: 1500
        var: CNR4TC_Avg
      LW_OUT_Avg:
        scalar: 108.10810810810811
        offset: 5.67 * 10**-8 * (CNR4TC_Avg + 273.15) ** 4
        lower: -200
        upper: 200
        var: CNR4TC_Avg
      SW_IN_NR01_Avg:
        scalar: 69.44444444444444
      SW_OUT_NR01_Avg:
        scalar: 60.24096385542168
      LW_IN_NR01_Avg:
        scalar: 88.49557522123894
      LW_OUT_NR01_Avg:
        scalar: 86.20689655172414

  # Known periods when the site was inaccessible.
  offline_periods:
    - []
